# Site settings##########################################
title: Tech Otakus Change The World
email: 271173141@qq.com
description: > # this means to ignore newlines until "baseurl:"
  我正是混沌的霸王，
  在深渊摇曳的炼狱业火，
  歪曲的昏暗火焰，
  混沌的深红黑暗，
  诱人发狂惨叫毁灭的灯火，
  用罪恶制裁罪恶黑色碎片在身上刻划，
  孤傲不逊对着世上法则露出獠牙吧,
  看吧这就是我真正的模样，
  残酷粗陋罪孽深重，
  吾之火焰名为"黑焰"Dark  and  Dark.
##########################################
url: "http://royleexh.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
#如果你的博客网站是类似http://localhost:4000/blog/index.html这样的路径。
#那么，在运行时，需要添加参数base-url来实现，
#比如：jekyll --base-url '/blog' --server
##########################################
#twitter_username: jekyllrb
github_username:  royleexh

# Build settings##########################################
#markdown: kramdown
highlighter: rouge
paginate: 8
