# Site settings##########################################
title: Tech Otakus Change The World
email: 271173141@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Master programmer, amateur superpowers, on my way to unknown pleasures.
##########################################
url: "http://royleexh.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
#如果你的博客网站是类似http://localhost:4000/blog/index.html这样的路径。
#那么，在运行时，需要添加参数base-url来实现，
#比如：jekyll --base-url '/blog' --server
##########################################
#twitter_username: jekyllrb
github_username:  royleexh

# Build settings##########################################
#markdown: kramdown
highlighter: rouge
paginate: 8
